### ISSUE TITLE
Listen 2.0 support

### ISSUE THREAD

**Issue by jonleighton** [jonleighton/spring-watcher-listen#1]
See discussion in https://github.com/rails/spring/pull/194. As a result, this project has been created and listen 2 support will be implemented here.

**Comment by jonleighton** [comment]
Sorry, closed this accidentally

**Comment by e2** [comment]
I should release master as 2.0.0 for now...

**Comment by e2** [comment]
Released as v2.0.0, should work without issues on Listen 2.x and Listen 3.x (preferred over Listen 1.x)
