### ISSUE TITLE
Creates too many processes and crashes my Mac

### ISSUE THREAD

**Issue by benaubin** [jonleighton/spring-watcher-listen#13]
When running my Rails app on a Macbook Air with about 0 ghz of cpu (I know... getting a new computer when they release the new Pro's), I have been getting a "System ran out of resources, can't fork any processes" error in all of my applications (or, they just quietly failed). Finally, I opened Activity Monitor and was able to find more then 500 `fsevent_watch` processes running (my computer has a maximum of 700 processes total). Doing a Google Search, I stumbled upon the [rb-fsevent gem](https://github.com/thibaudgg/rb-fsevent). Looking at my `Gemfile.lock`, I was able to track it down to this gem (as you depend on [listen](https://github.com/guard/listen) which depends on rb-fsevent).

I have removed the gem from my gemfile for the time being. This solved the problem, even though Active Support uses the listen gem as well. I believe that it might be because the processes are not properly closed when spring is stopped.

Please let me know if a fix is found.

I also reported this directly to the rails project on GitHub: https://github.com/rails/rails/issues/26158

**Comment by e2** [comment]
If you're talking about development mode, then maybe you have multiple
servers running on multiple folders. This increase the amount of
services, though they shouldn't be running.

There are some patches pending to fix maybe some of these issue (they
are a lot of work, so I'll need to find time - there are patches in
one of the recent issues).

**Comment by benaubin** [comment]
@e2 I am only running a single server, although it has multiple modules. I also am using Resque and Clockwork (and often times the Rails console), all of which load my environment.

**Comment by rvirani1** [comment]
+1

**Comment by benaubin** [comment]
Sorry about the late reply, but it looks like it's not this gem which breaks my laptop, but either ActiveSupport's implementation, or the listen gem itself.
