### ISSUE TITLE
Any way to disable the gem at runtime?

### ISSUE THREAD

**Issue by dreyks** [jonleighton/spring-watcher-listen#14]
Some systems do not support listen. Windows Subsystem for Linux (Bash on Ubuntu on Windows) has a flawed fd, though the `RUBY_PLATFORM` is reported as `x86_64-linux`, so I can't use `platform` in Gemfile.

Spring autorequires all the `/^spring-/` gems from the Gemfile, so `require: false` doesn't do a thing too

Is there a way to turn off the gem without touching the Gemfile? Lke Rails has `config.file_watcher` option

**Comment by e2** [comment]
You can probably switch to a non-listen watcher with:

``` ruby
Spring.watch_via = :polling
```
