### ISSUE TITLE
Enable regular build on Travis?

### ISSUE THREAD

**Issue by junaruga** [jonleighton/spring-watcher-listen#17]
Can you enable regular automatic build on Travis for master branch?

Right now it looks not enabled.
https://travis-ci.org/jonleighton/spring-watcher-listen/branches

Because I faced below error on my pull-request: https://github.com/jonleighton/spring-watcher-listen/pull/16 .
I want to know current master branch's situation.

```
 1) Error:
AcceptanceTest#test_app_gets_reloaded_even_with_a_ton_of_boot_output:
Errno::EBADF: Bad file descriptor
```

As we are using latest master `spring` for the testing, I think that enabling it is useful.

https://github.com/jonleighton/spring-watcher-listen/blob/master/Gemfile#L6

**Comment by rafaelfranca** [comment]
Enabled now
