### ISSUE TITLE
Using RuboCop?

### ISSUE THREAD

**Issue by utkarsh2102** [jonleighton/spring-watcher-listen#23]
Hi @jonleighton,

Thanks for maintaining this so far! :rocket: 

However, whilst trying to maintain and ship this in Debian, we found some problematic parts.
Would you be interested in using RuboCop? If so, I'd be happy to raise a PR :smile:

**Comment by rafaelfranca** [comment]
I'm ok to use Rubocop, but not sure how that would fix problematic parts. But if you want to send a PR, please
