### ISSUE TITLE
Release version that supports 4.0 and above

### ISSUE THREAD

**Issue by technicalpickles** [jonleighton/spring-watcher-listen#27]
I wanted to give this a try, but I'm getting this from bundler:

```
Bundler could not find compatible versions for gem "spring":
  In snapshot (Gemfile.lock):
    spring (>= 3.0.0)

  In Gemfile:
    spring

    spring-commands-rspec was resolved to 1.0.4, which depends on
      spring (>= 0.9.1)

    spring-watcher-listen was resolved to 2.0.0, which depends on
      spring (~> 1.2)
```

It looks like https://github.com/jonleighton/spring-watcher-listen/pull/26 addresses this, so could we get a release with it?

**Comment by pjg** [comment]
This issue should now read "Release version that supports spring v4.0".

**Comment by kroehre** [comment]
What's blocking this? @rafaelfranca
