### ISSUE TITLE
Couldn't cleanly terminate all actors in 2 seconds

### ISSUE THREAD

**Issue by noahsw** [jonleighton/spring-watcher-listen#7]
When adding 2.0 to my Gemfile, I get this error every time I exit `rails console`. This is the most related info I could find: https://github.com/celluloid/celluloid/issues/468

```
irb(main):002:0> exit
E, [2015-07-07T22:58:27.706170 #75560] ERROR -- : Couldn't cleanly terminate all actors in 2 seconds!
```

**Comment by e2** [comment]
Switch to using Listen 3.x - it doesn't use Celluloid anymore.

The only reason to use Listen 2.x is if you need TCP - if there are issues with Listen 3.x please report them ASAP, thanks!.
