### ISSUE TITLE
Add why? to README

### ISSUE THREAD

**Issue by neves** [jonleighton/spring-watcher-listen#9]
Would be nice a little explanation about why using listen is better.
Does spring run faster?
Does it use less machine resources?

**Comment by e2** [comment]
Thanks - I added a small note in the README. Let me know if it's enough.

**Comment by neves** [comment]
Thanks. that means it's not perceptible in small projects?

**Comment by e2** [comment]
@neves - best to test for your situation, since there are too many variables. E.g. certain setups on OSX can be very slow. You can check out the Listen doc/wiki about performance issues to get more info.
